Repository gardener/gardener-extension-os-gardenlinux, pull requests merged in 2021-06, with the labels that each got.

#32 Update the k8s.io dependencies in the replace directive as well
  go.mod
  go.sum
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
  vendor/k8s.io/api/apiserverinternal/v1alpha1/generated.pb.go
  vendor/k8s.io/api/apps/v1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta2/generated.pb.go
  vendor/k8s.io/api/authentication/v1/generated.pb.go
  vendor/k8s.io/api/authentication/v1beta1/generated.pb.go
  vendor/k8s.io/api/authorization/v1/generated.pb.go
  vendor/k8s.io/api/authorization/v1beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta2/generated.pb.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1beta1/generated.pb.go
  vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
  vendor/k8s.io/api/certificates/v1/generated.pb.go
  vendor/k8s.io/api/certificates/v1beta1/generated.pb.go
  vendor/k8s.io/api/coordination/v1/generated.pb.go
  vendor/k8s.io/api/coordination/v1beta1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/discovery/v1alpha1/generated.pb.go
  vendor/k8s.io/api/discovery/v1beta1/generated.pb.go
  vendor/k8s.io/api/events/v1/generated.pb.go
  vendor/k8s.io/api/events/v1beta1/generated.pb.go
  vendor/k8s.io/api/extensions/v1beta1/generated.pb.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/generated.pb.go
  vendor/k8s.io/api/flowcontrol/v1beta1/generated.pb.go
  vendor/k8s.io/api/networking/v1/generated.pb.go
  vendor/k8s.io/api/networking/v1beta1/generated.pb.go
  vendor/k8s.io/api/node/v1/generated.pb.go
  vendor/k8s.io/api/node/v1alpha1/generated.pb.go
  vendor/k8s.io/api/node/v1beta1/generated.pb.go
  vendor/k8s.io/api/policy/v1beta1/generated.pb.go
  vendor/k8s.io/api/rbac/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1alpha1/generated.pb.go
  vendor/k8s.io/api/rbac/v1beta1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go
  vendor/k8s.io/api/storage/v1/generated.pb.go
  vendor/k8s.io/api/storage/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/generated.pb.go
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#33 Use dedicated secret for the sample OSC
  README.md
  example/30-secret.yaml
  example/40-operatingsystemconfig.yaml
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, os/garden-linux, reviewed/lgtm, size/xs

#31 landscaper integration
  .ci/component_descriptor
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-executions.yaml
  .landscaper/resources.yaml
Labels: kind/enhancement, lifecycle/rotten, needs/changes, needs/ok-to-test, needs/review, os/garden-linux, size/s

#35 Update golang to 1.16.5
  Dockerfile
Labels: needs/ok-to-test, os/garden-linux, reviewed/lgtm, size/xs

#37 Update README.md
  README.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#39 Small improvement in Github template generation
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  Makefile
  hack/update-github-templates.sh
Labels: area/os, needs/ok-to-test, os/garden-linux, reviewed/lgtm, size/xs
