Repository gardener/gardener-extension-os-gardenlinux, pull requests merged in 2021-08, with the labels that each got.

#44 Fix `oscommon` link to g/g repo
  README.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#38 Rename blueprint
  .landscaper/resources.yaml
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, os/garden-linux

#46 Fix gardenlinux team name in CODEOWNERS
  CODEOWNERS
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#45 Initialize containerd config.toml file as early as possible
  pkg/generator/templates/cloud-init.gardenlinux.template
  pkg/generator/testfiles/containerd-bootstrap
Labels: area/os, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, os/garden-linux
