Repository gardener/gardener-extension-os-gardenlinux, pull requests merged in 2021-07, with the labels that each got.

#40 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, area/os, kind/enhancement, needs/ok-to-test, needs/review, os/garden-linux, size/xs

#43 Make leader election resource lock configurable and default to leases
  charts/gardener-extension-os-gardenlinux/templates/deployment.yaml
  charts/gardener-extension-os-gardenlinux/values.yaml
  cmd/gardener-extension-os-gardenlinux/app/app.go
  example/controller-registration.yaml
  go.mod
  vendor/modules.txt
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#42 Enable leader election in local setup
  Makefile
Labels: area/dev-productivity, area/os, kind/enhancement, needs/ok-to-test, os/garden-linux, reviewed/lgtm, size/xs
