Repository gardener/gardener-extension-os-gardenlinux, pull requests merged in 2022-08, with the labels that each got.

#67 assign image responsible
  .ci/pipeline_definitions
Labels: area/os, needs/ok-to-test, reviewed/lgtm, size/xs, os/garden-linux

#68 Bump golang version to 1.17.13
  Dockerfile
Labels: area/os, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, os/garden-linux

#66 Remove install-requirement and use tools.mk
  .gitignore
  Dockerfile
  Makefile
  hack/tools/bin/.gitkeep
Labels: area/os, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, os/garden-linux
