Repository gardener/gardener-extension-os-gardenlinux, pull requests merged in 2023-05, with the labels that each got.

#90 Correct the email for the gardener-robot-ci-1 user
  .github/workflows/vendor_gardener.yaml
Labels: area/os, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, os/garden-linux

#93 Adapt `NetworkPolicy`s
  charts/gardener-extension-os-gardenlinux/templates/service.yaml
  example/controller-registration.yaml
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#96 Add dependabot golang updates to Dockerfile
  .github/dependabot.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, os/garden-linux
