Repository gardener/gardener-extension-os-gardenlinux, pull requests merged in 2025-08, with the labels that each got.

#282 chore: remove vendor references from REUSE.toml
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/ISC.txt
  LICENSES/MIT.txt
  LICENSES/MPL-2.0.txt
  REUSE.toml
Labels: area/os, kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, size/xl, os/garden-linux

#288 Add label-based trust to head-update build job pull_request_target builds
  .github/workflows/build.yaml
  .github/workflows/dev_build.yaml
  .github/workflows/non-release.yaml
Labels: area/dev-productivity, kind/regression, needs/review, reviewed/ok-to-test, size/s

#289 Update CI build status badge (again)
  README.md
Labels: area/os, kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, size/xs, os/garden-linux
